name: Check ChangeLog

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check ChangeLog
        run: |
          perl scripts/checkchangelog.pl
          perl scripts/checkpanic.pl