[workspace]
resolver = "2"
members = [
    "crates/capability-protocol",
    "crates/certificate",
    "crates/certificate-database",
    "crates/driver-control-protocol",
    "crates/http-client",
    "crates/linux-gui-protocol",
    "crates/net-device-protocol",
    "crates/network-stack",
    "crates/tls-client",
    "crates/user-database",
    "crates/user-protocol",
    "crates/virtio-gpu-protocol",
    "crates/viewkit-gpu-protocol",
    "crates/syscall",
    "crates/runtime",
    "crates/signature-protocol",
    "crates/platform",
    "crates/newlib-runtime",
]

[workspace.package]
edition = "2024"
version = "0.1.0"

[patch.crates-io]
libc = { git = "https://github.com/mochiOS/libc", package = "libc" }
mnu-abi = { git = "https://github.com/mochiOS/mnu", package = "mnu-abi" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
