//! システムコール ABI の共通定義

pub use mnu_abi::{
    SyscallNumber, EACCES, EAGAIN, EBADF, EEXIST, EFAULT, EINVAL, EIO, EISDIR, EMFILE, ENODATA,
    ENOENT, ENOMEM, ENOSPC, ENOSYS, ENOTDIR, ENOTSUP, ENOTTY, ENXIO, EPERM, EPIPE, ERANGE, ESRCH,
    SUCCESS,
};
