[package]
name = "mochios-posix-client"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"

[dependencies]
mochi-user-platform = { path = "../platform", optional = true, default-features = false }
mochi-user-syscall = { path = "../syscall", optional = true }
mochios-posix-protocol = { path = "../posix-protocol" }
mochios-filesystem-protocol = { path = "../filesystem-protocol" }

[features]
default = ["endpoint", "fd-table"]
endpoint = ["dep:mochi-user-platform"]
syscall-endpoint = ["dep:mochi-user-syscall"]
fd-table = []

[lib]
path = "src/lib.rs"
