[package]
name = "mochios-posix-client"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"

[dependencies]
mochi-user-platform = { path = "../platform", optional = true, default-features = false }
mochios-posix-protocol = { path = "../posix-protocol" }

[features]
default = ["endpoint"]
endpoint = ["dep:mochi-user-platform"]

[lib]
path = "src/lib.rs"
