[service]
id = "core.service"
name = "Core Service"
entry = "entry"
type = "system"
autostart = false
order = 0

[capabilities]
required = [
  "ipc.server",
  "service.control",
  "process.spawn",
    "fs.read.all",
  "system.info.read"
]

optional = []
